Revert "Try to fix MyMoneyException on FreeBSD"
This reverts commit 8e32f27115265ae231dc410491b42dc87e56ba8d.

It does not solve the problem and fails for me with the following error:

/home/thb/devel/kmymoney/kmymoney/mymoney/mymoneyexception.h:64:3:
error: exception specification of explicitly defaulted copy constructor
does not match the calculated one