Include missing headers to fix build with Qt 5.5
Otherwise it fails with "...kmymoney/plugins/onlinetasks/interfaces/
converter/onlinetaskconverter.h:95:42: error: expected identifier
before string constant Q_DECLARE_INTERFACE(onlineTaskConverter,
"org.kmymoney.plugin.onlinetaskconverter");" and
"kmymoney-scm/kmymoney/mymoney/mymoneycategory.cpp:131:7: error:
ambiguous overload for 'operator<<' (operand types are 'QDataStream'
and 'int') s << (qint32)0;"

REVIEW: 123954