kbanking: Fix build without qtquick1
This accidentally worked when I still had qtquick1 installed. Without
it the build fails with "ui_chiptandialog.h:13:42: fatal error:
QtDeclarative/QDeclarativeView: No such file or directory".
The build system doesn't search for it and isn't really necessary
anymore so I removed the unused <class> part from chiptandialog.ui and
used the appropriate enum from QtQuickWidgets.

REVIEW: 126536