Fix method signature problem
The base class expects a more generic model type. Otherwise, newer
compiler complain about the fact that the method is shadowed. Since we
expect a somewhat different setup, we make sure to print out a warning
to the console for developers.

/builds/office/kmymoney/_build/kmymoney/widgets/kmm_base_widgets_autogen/EWIEGA46WW/../../../../../kmymoney/widgets/kmymoneyaccountcombo.h:66:10:
error: 'KMyMoneyAccountCombo::setModel' hides overloaded virtual
function [-Werror,-Woverloaded-virtual]
   66 |     void setModel(QSortFilterProxyModel *model);
      |          ^
/usr/local/include/qt6/QtWidgets/qcombobox.h:116:18: note: hidden
overloaded virtual function 'QComboBox::setModel' declared here: type
mismatch at 1st parameter ('QAbstractItemModel *' vs
'QSortFilterProxyModel *')
  116 |     virtual void setModel(QAbstractItemModel *model);
      |                  ^