Move kvpCount() instantiation to the .cpp file to fix compile
With clang 21.1.4 at least this fixes compile error:

```
mymoneygncreader.cpp
In file included from /data/KDE/src/kde/office/kmymoney/kmymoney/plugins/gnc/import/mymoneygncreader.cpp:12:
In file included from /data/KDE/src/kde/office/kmymoney/kmymoney/plugins/gnc/import/mymoneygncreader.h:138:
In file included from /usr/include/qt6/QtCore/QDate:1:
In file included from /usr/include/qt6/QtCore/qdatetime.h:8:
In file included from /usr/include/qt6/QtCore/qcalendar.h:10:
In file included from /usr/include/qt6/QtCore/qlocale.h:8:
In file included from /usr/include/qt6/QtCore/qvariant.h:10:
In file included from /usr/include/qt6/QtCore/qmetatype.h:11:
In file included from /usr/include/qt6/QtCore/qbytearray.h:11:
/usr/include/qt6/QtCore/qarraydata.h:177:87: error: invalid application of 'sizeof' to an incomplete type 'GncKvp'
  177 |         return (QtPrivate::MaxAllocSize - sizeof(QtPrivate::AlignedQArrayData) - 1) / sizeof(T);
      |                                                                                       ^~~~~~~~~
/usr/include/qt6/QtCore/qlist.h:446:57: note: in instantiation of member function 'QTypedArrayData<GncKvp>::maxSize' requested here
  446 |     static constexpr qsizetype maxSize() { return Data::maxSize(); }
      |                                                         ^
/usr/include/qt6/QtCore/qlist.h:450:36: note: in instantiation of member function 'QList<GncKvp>::maxSize' requested here
  450 |         constexpr size_t MaxSize = maxSize();
      |                                    ^
/usr/include/qt6/QtCore/qlist.h:455:57: note: in instantiation of member function 'QList<GncKvp>::size' requested here
  455 |     constexpr qsizetype count() const noexcept { return size(); }
      |                                                         ^
/data/KDE/src/kde/office/kmymoney/kmymoney/plugins/gnc/import/mymoneygncreader.h:257:27: note: in instantiation of member function 'QList<GncKvp>::count' requested here
  257 |         return (m_kvpList.count());
      |                           ^
/data/KDE/src/kde/office/kmymoney/kmymoney/plugins/gnc/import/mymoneygncreader.h:181:7: note: forward declaration of 'GncKvp'
  181 | class GncKvp;
      |       ^
In file included from /data/KDE/src/kde/office/kmymoney/kmymoney/plugins/gnc/import/mymoneygncreader.cpp:12:
In file included from /data/KDE/src/kde/office/kmymoney/kmymoney/plugins/gnc/import/mymoneygncreader.h:138:
In file included from /usr/include/qt6/QtCore/QDate:1:
In file included from /usr/include/qt6/QtCore/qdatetime.h:8:
In file included from /usr/include/qt6/QtCore/qcalendar.h:10:
In file included from /usr/include/qt6/QtCore/qlocale.h:8:
In file included from /usr/include/qt6/QtCore/qvariant.h:12:
In file included from /usr/include/qt6/QtCore/qdebug.h:41:
/usr/include/qt6/QtCore/qlist.h:450:26: error: constexpr variable 'MaxSize' must be initialized by a constant expression
  450 |         constexpr size_t MaxSize = maxSize();
      |                          ^         ~~~~~~~~~
/usr/include/qt6/QtCore/qlist.h:455:57: note: in instantiation of member function 'QList<GncKvp>::size' requested here
  455 |     constexpr qsizetype count() const noexcept { return size(); }
      |                                                         ^
/data/KDE/src/kde/office/kmymoney/kmymoney/plugins/gnc/import/mymoneygncreader.h:257:27: note: in instantiation of member function 'QList<GncKvp>::count' requested here
  257 |         return (m_kvpList.count());
      |                           ^
2 errors generated.
```

(cherry picked from commit b429ac275e9ebde2b234e2c33cce936beb8589f2)