Build against latest Alkimia on CI
@stable (which is currently 8.1) is apparently not found by CI and
latest works just as good.

$ python3 -u ci-utilities/run-ci-build.py --project $CI_PROJECT_NAME
--branch $CI_COMMIT_REF_NAME --platform Linux/Qt5/Shared
Traceback (most recent call last):
File "/builds/office/kmymoney/ci-utilities/run-ci-build.py", line 111,
in <module>
dependenciesToUnpack = packageRegistry.retrieveDependencies(
projectBuildDependencies )
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/builds/office/kmymoney/ci-utilities/components/Package.py",
line 201, in retrieveDependencies
raise Exception("Unable to locate requested dependency in the
registry: {} (branch: {})".format( identifier, branch ))
Exception: Unable to locate requested dependency in the registry:
alkimia (branch: 8.1)