Fix build with QtWebEngine
Summary:
Pull in <config-kmymoney.h>, which has the #define ENABLE_WEBENGINE,
otherwise the build fails with "khomeview_p.h:45:10: fatal error:
KWebView: No such file or directory".
Additionally fix another build error and access m_currentPrinter via
the d pointer.

Test Plan: Builds with -DENABLE_WEBENGINE:BOOL=TRUE

Reviewers: #kmymoney, wojnilowicz

Differential Revision: https://phabricator.kde.org/D10479